"""
Generate figures for the GitHub Pages site documenting the
mxbai-embed-large [UNK] token defect.

Produces:
  - docs/figures/collision_heatmap.png
  - docs/figures/diacritic_vs_plain.png
  - docs/figures/collision_count_over_threshold.png
  - docs/figures/token_analysis.png

docs/index.html is NOT regenerated by this script anymore — it is
hand-edited. The stale HTML template is kept in generate_html() for
historical reference only and is no longer wired into main().

Usage:
  python scripts/generate_defect_page.py   # regenerate figures from live Ollama
"""

import csv
import io
import json
import math
import os
import sys
import argparse
from pathlib import Path
from datetime import datetime, timezone

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
FIG_DIR = DOCS / "figures"
CSV_PATH = ROOT / "collisions.csv"

OLLAMA_URL = "http://localhost:11434/api/embed"
MODEL = "mxbai-embed-large"

# Palette — matches the CSS variables in docs/index.html so the figures
# visually tie into the site. Parchment background, muted terracotta
# accent (replaces the previous harsh #e74c3c), steel blue, sage.
PAL_BG = "#f6f2ec"
PAL_SURFACE = "#efe9df"
PAL_TEXT = "#2d2a26"
PAL_DIM = "#6e6a61"
PAL_ACCENT = "#b8553a"    # muted terracotta
PAL_BLUE = "#3f6487"      # muted steel blue
PAL_GREEN = "#5b7a4a"     # sage
PAL_BORDER = "#d9d1c1"

# Use the palette globally so every chart follows it
plt.rcParams.update({
    "figure.facecolor": PAL_BG,
    "axes.facecolor": PAL_BG,
    "savefig.facecolor": PAL_BG,
    "axes.edgecolor": PAL_BORDER,
    "axes.labelcolor": PAL_TEXT,
    "axes.titlecolor": PAL_TEXT,
    "text.color": PAL_TEXT,
    "xtick.color": PAL_TEXT,
    "ytick.color": PAL_TEXT,
    "grid.color": PAL_BORDER,
    "font.family": "DejaVu Sans",  # ships with matplotlib, has full unicode coverage
    "font.size": 10,
})

# ── Diacritical test words (the core of the defect) ──────────────────────
DIACRITIC_WORDS = [
    "Hokkaidō", "Tōkyō", "Jinmyōchō", "Shōtoku", "Shōtai",
    "kugyō", "România", "Éire", "Djazaïr", "Filasṭīn",
    "Aikanã", "naïve", "Zürich", "café", "résumé",
    "São Paulo", "Malmö", "Gdańsk", "Łódź", "Dvořák",
]

PLAIN_WORDS = [
    "Hokkaido", "Tokyo", "Jinmyocho", "Shotoku", "Shotai",
    "kugyo", "Romania", "Eire", "Djazair", "Filastin",
    "Aikana", "naive", "Zurich", "cafe", "resume",
    "Sao Paulo", "Malmo", "Gdansk", "Lodz", "Dvorak",
]

CONTROL_WORDS = [
    "Berlin", "quantum physics", "cat", "democracy", "bicycle",
    "economics", "shrine", "emperor", "photosynthesis", "river",
]


def embed_ollama(texts):
    """Get embeddings from local Ollama."""
    import urllib.request
    payload = json.dumps({"model": MODEL, "input": texts}).encode()
    req = urllib.request.Request(
        OLLAMA_URL, data=payload, headers={"Content-Type": "application/json"}
    )
    with urllib.request.urlopen(req, timeout=120) as resp:
        return json.loads(resp.read())["embeddings"]


def cosine(a, b):
    dot = sum(x * y for x, y in zip(a, b))
    na = math.sqrt(sum(x * x for x in a))
    nb = math.sqrt(sum(x * x for x in b))
    return dot / (na * nb) if na and nb else 0.0


def load_csv():
    """Load existing collisions.csv."""
    rows = []
    with open(str(CSV_PATH), encoding="utf-8") as f:
        for r in csv.DictReader(f):
            rows.append(r)
    return rows


def run_live_embeddings():
    """Re-embed everything with Ollama and return similarity matrix data."""
    all_words = DIACRITIC_WORDS + PLAIN_WORDS + CONTROL_WORDS
    unique = list(dict.fromkeys(all_words))
    print(f"Embedding {len(unique)} texts with {MODEL}...")
    vecs = embed_ollama(unique)
    word2vec = dict(zip(unique, vecs))
    return word2vec


# ── Figure generators ────────────────────────────────────────────────────

def fig_collision_heatmap(word2vec):
    """Heatmap showing cosine similarity between all diacritical words.

    The headline figure: every diacritical word collapses onto every
    other diacritical word at cosine ~1.0. The one ASCII outlier
    ("São Paulo" has a space that resets the WordPiece tokenizer on
    its second word) sits at ~0.5, proving the effect is tokenizer-
    driven rather than semantic.
    """
    words = [w for w in DIACRITIC_WORDS if w in word2vec]
    n = len(words)
    matrix = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            matrix[i, j] = cosine(word2vec[words[i]], word2vec[words[j]])

    fig, ax = plt.subplots(figsize=(13, 11))

    # Custom colormap: parchment → sage (low) to terracotta (high).
    # Strong saturation at the top to make the "all-red-at-1.0" read
    # visible at thumbnail resolution.
    from matplotlib.colors import LinearSegmentedColormap
    cmap = LinearSegmentedColormap.from_list(
        "parchment_heat",
        [PAL_GREEN, "#c7b587", "#d49560", PAL_ACCENT, "#8a3820"],
    )
    im = ax.imshow(matrix, cmap=cmap, vmin=0.3, vmax=1.0, aspect="auto")

    ax.set_xticks(range(n))
    ax.set_yticks(range(n))
    ax.set_xticklabels(words, rotation=45, ha="right", fontsize=10)
    ax.set_yticklabels(words, fontsize=10)

    for i in range(n):
        for j in range(n):
            color = "white" if matrix[i, j] > 0.75 else PAL_TEXT
            ax.text(j, i, f"{matrix[i, j]:.2f}", ha="center", va="center",
                    fontsize=7, color=color)

    cbar = fig.colorbar(im, ax=ax, shrink=0.85, pad=0.02)
    cbar.set_label("Cosine Similarity", fontsize=11)
    cbar.outline.set_edgecolor(PAL_BORDER)

    ax.set_title(
        "Every diacritical word collapses onto every other diacritical word\n"
        "Cosine similarity ≈ 1.00 for 361 of 380 off-diagonal cells",
        fontsize=14, pad=18, color=PAL_TEXT, fontweight="bold",
    )
    plt.tight_layout()
    path = FIG_DIR / "collision_heatmap.png"
    fig.savefig(str(path), dpi=160, bbox_inches="tight", facecolor=PAL_BG)
    plt.close(fig)
    print(f"  Saved {path}")


def fig_diacritic_vs_plain(word2vec):
    """Bar chart: diacritical word vs its plain ASCII equivalent.

    Blue bars: same word in both forms (Hokkaidō vs Hokkaido) — what
    a working model should score near 1.0.
    Terracotta bars: diacritical word vs a different diacritical word —
    what a working model should score near 0.4-0.5.
    Reality: the terracotta bars are at 1.0 and the blue bars are
    at ~0.5. The model says a word is more similar to an unrelated
    foreign word than to its own ASCII form.
    """
    pairs = list(zip(DIACRITIC_WORDS, PLAIN_WORDS))
    pairs = [(d, p) for d, p in pairs if d in word2vec and p in word2vec]

    labels = [f"{d}\nvs {p}" for d, p in pairs]
    sims = [cosine(word2vec[d], word2vec[p]) for d, p in pairs]

    # Cross-collision: diacritical word vs a different diacritical word
    cross_sims = []
    for i, (d, _) in enumerate(pairs):
        other_d = pairs[(i + 3) % len(pairs)][0]
        cross_sims.append(cosine(word2vec[d], word2vec[other_d]))

    fig, ax = plt.subplots(figsize=(15, 7))
    x = np.arange(len(labels))
    w = 0.38

    ax.bar(
        x - w / 2, sims, w,
        label="Same word: diacritic vs plain  (should be ≈1.0)",
        color=PAL_BLUE, edgecolor=PAL_BG, linewidth=1.2,
    )
    ax.bar(
        x + w / 2, cross_sims, w,
        label="Different word: diacritic vs diacritic  (should be ≈0.4)",
        color=PAL_ACCENT, edgecolor=PAL_BG, linewidth=1.2,
    )

    ax.axhline(y=0.95, color=PAL_ACCENT, linestyle="--", alpha=0.6,
               linewidth=1.2, label="Collision threshold (0.95)")
    ax.axhline(y=0.5, color=PAL_GREEN, linestyle="--", alpha=0.5,
               linewidth=1.0, label="Expected baseline (~0.5)")

    ax.set_ylabel("Cosine Similarity", fontsize=12)
    ax.set_title(
        'The paradox: "Hokkaidō" is closer to "Éire" than to "Hokkaido"\n'
        "Unrelated diacritical words (red) score higher than matched ASCII pairs (blue)",
        fontsize=14, pad=16, color=PAL_TEXT, fontweight="bold",
    )
    ax.set_xticks(x)
    ax.set_xticklabels(labels, fontsize=8.5, rotation=30, ha="right")
    ax.set_ylim(0, 1.15)
    ax.legend(fontsize=10, loc="upper right", framealpha=0.92,
              edgecolor=PAL_BORDER, facecolor=PAL_SURFACE)
    ax.grid(True, alpha=0.35, axis="y", color=PAL_BORDER)
    ax.set_axisbelow(True)

    plt.tight_layout()
    path = FIG_DIR / "diacritic_vs_plain.png"
    fig.savefig(str(path), dpi=160, bbox_inches="tight", facecolor=PAL_BG)
    plt.close(fig)
    print(f"  Saved {path}")


def fig_threshold_sweep(word2vec):
    """How many collisions at each cosine threshold.

    Shows that the collision isn't a soft blur around 1.0 — it's a
    hard plateau. Even at a very strict threshold of 0.99, almost
    every diacritical pair still counts as a collision.
    """
    words = [w for w in DIACRITIC_WORDS if w in word2vec]
    all_sims = []
    for i in range(len(words)):
        for j in range(i + 1, len(words)):
            all_sims.append(cosine(word2vec[words[i]], word2vec[words[j]]))

    thresholds = np.arange(0.80, 1.001, 0.005)
    counts = [sum(1 for s in all_sims if s >= t) for t in thresholds]
    count_at_95 = sum(1 for s in all_sims if s >= 0.95)
    total = len(words) * (len(words) - 1) // 2

    fig, ax = plt.subplots(figsize=(11, 6))
    ax.fill_between(thresholds, counts, alpha=0.35, color=PAL_ACCENT)
    ax.plot(thresholds, counts, "o-", color=PAL_ACCENT,
            markersize=4, linewidth=1.8)

    ax.axvline(x=0.95, color=PAL_ACCENT, linestyle="--", alpha=0.7, linewidth=1.3)
    ax.annotate(
        f"{count_at_95} of {total} pairs\ncollide at cosine ≥ 0.95\n({count_at_95/total:.0%} collision rate)",
        xy=(0.95, count_at_95),
        xytext=(0.82, total * 0.55),
        arrowprops=dict(arrowstyle="->", color=PAL_ACCENT, lw=1.5),
        fontsize=11, color=PAL_TEXT,
        bbox=dict(boxstyle="round,pad=0.5", facecolor=PAL_SURFACE,
                  edgecolor=PAL_BORDER),
    )

    ax.axhline(y=total, color=PAL_DIM, linestyle=":", alpha=0.6)
    ax.text(0.805, total + 2, f"Total pairs in 20-word sample: {total}",
            fontsize=10, color=PAL_DIM)

    ax.set_xlabel("Cosine Similarity Threshold", fontsize=12)
    ax.set_ylabel("Number of Colliding Pairs", fontsize=12)
    ax.set_title(
        "This is a hard collapse, not gradual degradation\n"
        "The curve is flat near its maximum — even at cosine ≥ 0.99, nearly all pairs still collide",
        fontsize=13.5, pad=14, color=PAL_TEXT, fontweight="bold",
    )
    ax.grid(True, alpha=0.35, color=PAL_BORDER)
    ax.set_axisbelow(True)
    plt.tight_layout()
    path = FIG_DIR / "collision_count_over_threshold.png"
    fig.savefig(str(path), dpi=160, bbox_inches="tight", facecolor=PAL_BG)
    plt.close(fig)
    print(f"  Saved {path}")


def fig_token_analysis(word2vec):
    """Three similarity distributions showing the [UNK] token dominance.

    Left panel (the smoking gun): every diacritical-diacritical pair
    sits at ~1.0. Middle panel: control words behave normally,
    distribution around ~0.5. Right panel: diacritical vs control
    sits at ~0.5, meaning the [UNK]-dominated vector has moderate
    similarity to every English word.
    """
    d_words = [w for w in DIACRITIC_WORDS if w in word2vec]
    c_words = [w for w in CONTROL_WORDS if w in word2vec]

    dd_sims, cc_sims, dc_sims = [], [], []
    for i in range(len(d_words)):
        for j in range(i + 1, len(d_words)):
            dd_sims.append(cosine(word2vec[d_words[i]], word2vec[d_words[j]]))
    for i in range(len(c_words)):
        for j in range(i + 1, len(c_words)):
            cc_sims.append(cosine(word2vec[c_words[i]], word2vec[c_words[j]]))
    for d in d_words:
        for c in c_words:
            dc_sims.append(cosine(word2vec[d], word2vec[c]))

    fig, axes = plt.subplots(1, 3, figsize=(16, 6), sharey=False)

    panels = [
        (axes[0], dd_sims,
         "Diacritical vs Diacritical",
         "All pairs collapse to ≈1.0",
         PAL_ACCENT),
        (axes[1], cc_sims,
         "Control vs Control  (ASCII baseline)",
         "Normal distribution around ≈0.5",
         PAL_BLUE),
        (axes[2], dc_sims,
         "Diacritical vs Control",
         "[UNK] vector has ≈0.5 similarity to any English word",
         PAL_GREEN),
    ]

    for ax, sims, title, subtitle, color in panels:
        if sims:
            ax.hist(
                sims, bins=24, range=(-0.05, 1.05),
                color=color, edgecolor=PAL_BG, linewidth=0.8, alpha=0.88,
            )
            ax.axvline(x=np.mean(sims), color=PAL_TEXT,
                       linestyle="--", linewidth=1.8)
            ax.text(
                0.97, 0.95,
                f"μ = {np.mean(sims):.3f}\nσ = {np.std(sims):.3f}\nn = {len(sims)}",
                transform=ax.transAxes, ha="right", va="top", fontsize=10,
                bbox=dict(boxstyle="round,pad=0.4", facecolor=PAL_SURFACE,
                          edgecolor=PAL_BORDER),
            )
        ax.set_title(f"{title}\n{subtitle}", fontsize=12,
                     color=PAL_TEXT, pad=10)
        ax.set_xlabel("Cosine Similarity", fontsize=11)
        ax.set_xlim(-0.1, 1.1)
        ax.grid(True, alpha=0.35, color=PAL_BORDER)
        ax.set_axisbelow(True)

    axes[0].set_ylabel("Pair Count", fontsize=11)

    fig.suptitle(
        "[UNK] token dominance: diacritical words cluster into a single point",
        fontsize=15, y=1.00, color=PAL_TEXT, fontweight="bold",
    )
    plt.tight_layout()
    path = FIG_DIR / "token_analysis.png"
    fig.savefig(str(path), dpi=160, bbox_inches="tight", facecolor=PAL_BG)
    plt.close(fig)
    print(f"  Saved {path}")


def generate_html(timestamp):
    """Generate the full HTML page."""
    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>mxbai-embed-large thinks "Hokkaidō" and "Éire" are the same word</title>
<style>
  :root {{
    --bg: #0d1117; --surface: #161b22; --card: #1c2333;
    --accent: #e74c3c; --text: #e6edf3; --dim: #8b949e;
    --green: #3fb950; --yellow: #d29922; --blue: #58a6ff;
    --border: #30363d;
  }}
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif;
    background: var(--bg); color: var(--text); line-height: 1.7;
    max-width: 960px; margin: 0 auto; padding: 2rem 1.5rem;
  }}
  h1 {{ color: var(--accent); font-size: 2rem; margin-bottom: 0.3rem; }}
  h2 {{
    color: var(--blue); font-size: 1.4rem; margin: 2.5rem 0 1rem;
    padding-bottom: 0.4rem; border-bottom: 1px solid var(--border);
  }}
  h3 {{ color: var(--green); margin: 1.5rem 0 0.5rem; }}
  p {{ margin-bottom: 1rem; }}
  a {{ color: var(--blue); text-decoration: none; }}
  a:hover {{ text-decoration: underline; }}
  code {{
    background: var(--surface); padding: 0.15rem 0.4rem; border-radius: 4px;
    font-family: 'Cascadia Code', 'Fira Code', monospace; font-size: 0.9em;
    color: var(--green); border: 1px solid var(--border);
  }}
  pre {{
    background: var(--surface); padding: 1rem; border-radius: 6px;
    overflow-x: auto; border: 1px solid var(--border); margin: 1rem 0;
  }}
  pre code {{ background: none; border: none; padding: 0; }}
  .alert {{
    background: rgba(231,76,60,0.1); border: 1px solid var(--accent);
    border-radius: 8px; padding: 1.2rem; margin: 1.5rem 0;
  }}
  .alert h3 {{ color: var(--accent); margin-top: 0; }}
  .info {{
    background: rgba(88,166,255,0.08); border: 1px solid rgba(88,166,255,0.3);
    border-radius: 8px; padding: 1.2rem; margin: 1.5rem 0;
  }}
  .figure {{
    background: var(--surface); border-radius: 8px; padding: 1rem;
    margin: 1.5rem 0; border: 1px solid var(--border); text-align: center;
  }}
  .figure img {{ max-width: 100%; height: auto; border-radius: 4px; }}
  .figure .caption {{ color: var(--dim); font-size: 0.9rem; margin-top: 0.7rem; }}
  .stats {{
    display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
    gap: 1rem; margin: 1.5rem 0;
  }}
  .stat {{
    background: var(--card); border-radius: 8px; padding: 1.2rem;
    text-align: center; border: 1px solid var(--border);
  }}
  .stat .number {{ font-size: 2rem; font-weight: bold; color: var(--accent); }}
  .stat .label {{ color: var(--dim); font-size: 0.85rem; }}
  table {{
    width: 100%; border-collapse: collapse; margin: 1rem 0;
    font-size: 0.9rem;
  }}
  th {{ background: var(--card); color: var(--blue); text-align: left;
       padding: 0.6rem 0.8rem; border-bottom: 2px solid var(--accent); }}
  td {{ padding: 0.5rem 0.8rem; border-bottom: 1px solid var(--border); }}
  tr:hover td {{ background: rgba(88,166,255,0.04); }}
  .collision {{ color: var(--accent); font-weight: bold; }}
  .safe {{ color: var(--green); }}
  footer {{ margin-top: 3rem; padding-top: 1rem; border-top: 1px solid var(--border);
            color: var(--dim); font-size: 0.85rem; }}
  @media (max-width: 600px) {{
    body {{ padding: 1rem; }}
    .stats {{ grid-template-columns: 1fr; }}
  }}
</style>
</head>
<body>

<h1 style="font-size:2.4rem;line-height:1.2">mxbai-embed-large thinks "Hokkaid&#x014d;" and "&#x00c9;ire" are the same word</h1>
<p style="color:var(--dim);font-size:1.1rem;margin-top:0.8rem">
  A top-10 MTEB embedding model has a tokenizer defect that makes every string with
  a diacritical mark produce the <em>same</em> vector. 147,687 confirmed cross-entity collisions.
  Zero benchmarks catch it.
  <br>Last updated: <strong>{timestamp}</strong>
</p>

<div class="alert">
  <h3>What is this?</h3>
  <p>
    <code>mxbai-embed-large</code> is one of the most popular open-source text embedding models
    (top 10 on MTEB). It has a critical tokenizer defect: any text containing diacritical marks
    (accented characters like o&#x0304;, e&#x0301;, u&#x0308;, etc.) gets mapped to the <code>[UNK]</code>
    token, and the resulting embedding is dominated by that single token's vector.
  </p>
  <p>
    <strong>Result:</strong> Completely unrelated words like "Hokkaid&#x014d;" (a Japanese island)
    and "&#x00c9;ire" (Ireland in Irish) produce <em>identical</em> embeddings (cosine similarity = 1.000).
    This defect is invisible to standard benchmarks like MTEB because they primarily use ASCII text.
  </p>
</div>

<div class="stats">
  <div class="stat">
    <div class="number">147,687</div>
    <div class="label">Cross-entity collisions</div>
  </div>
  <div class="stat">
    <div class="number">1.000</div>
    <div class="label">Cosine similarity (unrelated words)</div>
  </div>
  <div class="stat">
    <div class="number">~0.48</div>
    <div class="label">Cosine to own ASCII equivalent</div>
  </div>
  <div class="stat">
    <div class="number">0</div>
    <div class="label">MTEB benchmarks that catch this</div>
  </div>
</div>

<h2>1. The Collision Heatmap</h2>
<p>
  Every cell shows the cosine similarity between two words containing diacritical marks.
  In a working embedding model, unrelated words should have low similarity (~0.3-0.5).
  Instead, nearly every pair is at or near <strong>1.0</strong>.
</p>
<div class="figure">
  <img src="figures/collision_heatmap.png" alt="Collision heatmap showing near-1.0 similarity between all diacritical words">
  <div class="caption">Figure 1: Cosine similarity heatmap. All diacritical words map to essentially the same vector.</div>
</div>

<h2>2. The Paradox: Unrelated Words Are More Similar Than the Same Word</h2>
<p>
  "Hokkaid&#x014d;" (with macron) has cosine similarity ~1.0 with "&#x00c9;ire" (completely unrelated),
  but only ~0.50 with "Hokkaido" (the same place, ASCII spelling). The diacritical mark doesn't
  just add noise &mdash; it <em>completely overwrites</em> the semantic content.
</p>
<div class="figure">
  <img src="figures/diacritic_vs_plain.png" alt="Bar chart comparing same-word and cross-word similarities">
  <div class="caption">Figure 2: Blue bars show similarity to the word's own ASCII form. Red bars show similarity to a random other diacritical word. Red is consistently higher.</div>
</div>

<h2>3. Collision Count by Threshold</h2>
<p>
  Even with a very strict threshold of 0.99, most diacritical word pairs still collide.
  This is not gradual degradation &mdash; it's a hard collapse to a single point in embedding space.
</p>
<div class="figure">
  <img src="figures/collision_count_over_threshold.png" alt="Graph showing collision counts remain high even at strict thresholds">
  <div class="caption">Figure 3: Number of colliding pairs at each cosine similarity threshold. The curve stays flat near the maximum.</div>
</div>

<h2>4. Distribution Analysis: The [UNK] Cluster</h2>
<p>
  Three histograms tell the full story:
</p>
<ul>
  <li><strong>Left (red):</strong> Diacritical vs diacritical &mdash; all clustered at ~1.0 (the defect)</li>
  <li><strong>Center (blue):</strong> Control vs control &mdash; normal distribution around ~0.5 (baseline)</li>
  <li><strong>Right (yellow):</strong> Diacritical vs control &mdash; shows the [UNK] vector has moderate similarity to everything</li>
</ul>
<div class="figure">
  <img src="figures/token_analysis.png" alt="Three histograms showing similarity distributions">
  <div class="caption">Figure 4: The diacritical-diacritical distribution is a spike at 1.0, not a bell curve. This is a tokenizer defect, not embedding noise.</div>
</div>

<h2>5. How It Happens</h2>

<div class="info">
<h3>The Mechanism</h3>
<p>mxbai-embed-large uses a WordPiece tokenizer. When it encounters characters outside its vocabulary (diacritical marks like &#x014d;, &#x00e9;, &#x00fc;, &#x0142;, etc.), the <em>entire token</em> containing that character becomes <code>[UNK]</code>.</p>

<p>For short strings like proper nouns, the [UNK] token dominates the final pooled embedding. Since every diacritical string maps to essentially the same sequence of [UNK] tokens, they all produce the same embedding vector.</p>

<pre><code># What the tokenizer sees:
"Hokkaidō"  → ["[CLS]", "[UNK]", "[SEP]"]
"Éire"      → ["[CLS]", "[UNK]", "[SEP]"]
"Zürich"    → ["[CLS]", "[UNK]", "[SEP]"]
"café"      → ["[CLS]", "[UNK]", "[SEP]"]

# All four produce the SAME embedding vector</code></pre>
</div>

<h2>6. Who Is Affected?</h2>

<table>
<tr><th>Domain</th><th>Impact</th><th>Example</th></tr>
<tr>
  <td>Multilingual NLP</td>
  <td class="collision">Critical</td>
  <td>Any language with diacritics (French, German, Japanese romaji, Polish, Czech, ...)</td>
</tr>
<tr>
  <td>Knowledge Graphs</td>
  <td class="collision">Critical</td>
  <td>Wikidata entities with non-ASCII labels become indistinguishable</td>
</tr>
<tr>
  <td>RAG / Retrieval</td>
  <td class="collision">High</td>
  <td>Documents about "Malm&#x00f6;" match queries about "Dvo&#x0159;&#x00e1;k"</td>
</tr>
<tr>
  <td>Semantic Search</td>
  <td class="collision">High</td>
  <td>Any product/person/place name with accented characters</td>
</tr>
<tr>
  <td>English-only</td>
  <td class="safe">Low</td>
  <td>Standard ASCII text works fine (which is why MTEB misses this)</td>
</tr>
</table>

<h2>7. Reproducing This</h2>
<pre><code># Install Ollama and pull the model
ollama pull mxbai-embed-large

# Clone the repo and run the demo
git clone https://github.com/EmmaLeonhart/latent-space-cartography.git
cd latent-space-cartography
python scripts/demo_collisions.py

# Output: collisions.csv showing the defect</code></pre>

<h2>8. What Should Be Done</h2>
<ol>
  <li><strong>Tokenizer fix:</strong> Replace unknown-character fallback with character-level tokenization or byte-level BPE</li>
  <li><strong>Benchmark gap:</strong> MTEB should include diacritical/multilingual string pairs as a robustness check</li>
  <li><strong>User workaround:</strong> Strip diacritical marks before embedding (loses linguistic information but prevents collisions)</li>
  <li><strong>Model choice:</strong> Use models with byte-level tokenizers (e.g., nomic-embed-text) for non-ASCII data</li>
</ol>

<h2>9. Context</h2>
<p>
  This defect was discovered during the
  <a href="https://github.com/EmmaLeonhart/latent-space-cartography">Latent Space Cartography</a>
  project, which applies Vector Symbolic Architecture (VSA) analysis to frozen text embeddings.
  When probing Wikidata entity embeddings for relational structure, the collision pattern was
  unmistakable: 147,687 cross-entity pairs at cosine &ge; 0.95, all involving diacritical text.
</p>
<p>
  The full analysis is documented in our paper:
  <em>"Emergent Vector Symbolic Operations in Frozen Text Embeddings"</em>
  (clawRxiv 2604.00859).
</p>

<footer>
  <p>
    <a href="https://github.com/EmmaLeonhart/latent-space-cartography">latent-space-cartography</a>
    &middot; {timestamp}
  </p>
</footer>

</body>
</html>"""
    path = DOCS / "index.html"
    path.write_text(html, encoding="utf-8")
    print(f"  Saved {path}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--live", action="store_true",
                        help="(default) Re-embed with Ollama. Kept for backwards "
                             "compatibility; this script always uses Ollama now.")
    args = parser.parse_args()
    _ = args  # kept for CLI compatibility

    FIG_DIR.mkdir(parents=True, exist_ok=True)

    print("Running live embeddings via Ollama...")
    try:
        word2vec = run_live_embeddings()
    except Exception as e:
        print(f"  Ollama not available ({e}).")
        print("  Start Ollama and pull mxbai-embed-large:")
        print("    ollama pull mxbai-embed-large")
        sys.exit(1)

    print("\nGenerating figures...")
    fig_collision_heatmap(word2vec)
    fig_diacritic_vs_plain(word2vec)
    fig_threshold_sweep(word2vec)
    fig_token_analysis(word2vec)

    print("\nDone. docs/index.html is hand-edited and was NOT touched.")
    print("If the site copy needs updating, edit docs/index.html directly.")


if __name__ == "__main__":
    main()
